<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <title>Certificate of Achievement</title>
    <style>
        body {
            font-family: 'Times New Roman', serif;
            background-color: #fff;
            margin: 0;
            padding: 0;
        }
        .certificate-container {
            width: 600px;
            margin: 50px auto;
            padding: 60px 60px 80px;
            border: 12px solid #592f2f;
            background-color: #fefefe;
            position: relative;
            box-shadow: 0 0 20px rgba(0,0,0,0.2);
            overflow: hidden;
        }
        /* Watermark logo centered, faint */
        .certificate-container::before {
            content: "";
            position: absolute;
            top: 50%;
            left: 50%;
            width: 300px;
            height: 300px;
            background: url("{{ asset('img/logo.jpg') }}") no-repeat center center;
            background-size: contain;
            opacity: 0.07;
            transform: translate(-50%, -50%);
            pointer-events: none;
            z-index: 0;
        }
        .certificate-header {
            position: relative;
            z-index: 1;
            text-align: center;
            margin-bottom: 40px;
        }
        .certificate-header img {
            height: 100px;
        }
        .certificate-title {
            font-size: 36px;
            font-weight: bold;
            text-transform: uppercase;
            margin-top: 20px;
            border-bottom: 2px solid #444;
            padding-bottom: 10px;
            display: inline-block;
        }
        .certificate-id {
            position: relative;
            z-index: 1;
            text-align: right;
            font-size: 14px;
            margin-bottom: 25px;
            color: #333;
        }
        .certificate-body {
            position: relative;
            z-index: 1;
            text-align: center;
            margin: 60px 0;
            color: #222;
        }
        .certificate-body h2 {
            margin: 20px 0;
            font-size: 28px;
        }
        .certificate-body h4 {
            font-size: 20px;
            font-weight: normal;
            color: #333;
        }
        .certificate-footer {
            position: relative;
            z-index: 1;
            display: flex;
            justify-content: space-between;
            align-items: flex-start;
            margin-top: 80px;
            font-size: 16px;
            text-align: center;
        }
        .signature-left {
            width: 30%;
            text-align: left;
        }
        .issued-date {
            width: 30%;
            text-align: center;
        }
        .signature-right {
            width: 30%;
            text-align: right;
        }
        .footer-note {
            position: relative;
            z-index: 1;
            text-align: center;
            margin-top: 50px;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="certificate-container">
        <div class="certificate-header">
            <img src="{{ asset('img/logo.jpg') }}" alt="Academy Logo" />
            <div class="certificate-title">Certificate of Achievement</div>
        </div>

        @php
            $certificationId = 'CERT-' . $certification->user_id . '-' . \Carbon\Carbon::parse($certification->issued_date)->format('Ymd') . '-' . strtoupper(substr($certification->certification_type, 0, 3));
        @endphp

        <div class="certificate-id">
            <strong>Certificate ID:</strong> {{ $certificationId }}
        </div>

        <div class="certificate-body">
            <h4>This is to certify that</h4>
            <h2>{{ $certification->user->name }}</h2>
            <h4>has successfully completed the</h4>
            <h2>{{ ucfirst($certification->certification_type) }} Program</h2>
            <h4>with honor and distinction.</h4>
        </div>

        <div class="certificate-footer">
            <div class="signature-left">
                _________________________<br>
                <strong>President</strong>
            </div>

            <div class="issued-date">
                <strong>Issued Date:</strong><br>
                {{ \Carbon\Carbon::parse($certification->issued_date)->format('F d, Y') }}
            </div>

            <div class="signature-right">
                _________________________<br>
                <strong>Chief Examiner</strong>
            </div>
        </div>

        <div class="footer-note">
            Generated by Karate Academy System
        </div>
    </div>
</body>
</html>
